### PR TITLE
The install protocol support is added.

### PR DESCRIPTION
**Pull request by priyama2**
Hereby we can use http,ftp,nfs as argument to the installation

### CODE REVIEW

**Comment by abdhaleegit** [comment]
looks like one unwanted config_parser.py is added..please remove it

**Comment by priyama2** [comment]
install protocol: nfs 
python3 installvm.py --host-ip xx.xx.xx.xx --host-name abc --host-gw xx.xx.xx.xx --host-netmask xx.xx.xx.xx --host-mac ab:cd:11:11:11 --lpar-hmc HMC --lpar-managed-system abc --lpar-partition-name abc1 --distro rhel_9.3 --host-disk=0235b1 --hmc-profile default_profile --hmc-userid xyz --hmc-password 111 --host-password  111 --kernel-params None --install-protocol nfs
ks file:
```
[root@powerkvm1-lp1 rhel]# cat rhel-ab:cd:11:11:11.ks
%pre
%end
url --url=nfs://xx.xx.xx.xx:1/crtl/repo/rhel/9.3le
text
keyboard --vckeymap=us --xlayouts='us'
lang en_US.UTF-8
rootpw --plaintext 111
skipx
timezone Asia/Kolkata --isUtc
zerombr
clearpart --all --initlabel --drives=/dev/disk/by-id/0235b1
bootloader   --location=mbr --boot-drive=/dev/disk/by-id/0235b1
ignoredisk --only-use=/dev/disk/by-id/dm-uuid-mpath-0235b1
autopart --type=lvm --fstype=ext4
services --enabled=NetworkManager,sshd
reboot
%packages
@core
kexec-tools
device-mapper-multipath
%end
%post
sed -i 's/#\?PermitRootLogin.*/PermitRootLogin yes/g' /etc/ssh/sshd_config;service sshd restart;multipath -t >/etc/multipath.conf;service multipathd start
%end
```
http:
python3 installvm.py --host-ip xx.xx.xx.xx --host-name abc --host-gw xx.xx.xx.xx --host-netmask xx.xx.xx.xx --host-mac ab:cd:11:11:11 --lpar-hmc HMC --lpar-managed-system abc --lpar-partition-name abc1 --distro rhel_9.3 --host-disk=0235b1 --hmc-profile default_profile --hmc-userid xyz --hmc-password 111 --host-password  111 --kernel-params None --install-protocol http

ksfile:
```
[root@powerkvm1-lp1 rhel]# cat rhel-ab:cd:11:11:11.ks
%pre
%end
url --url=http://xx.xx.xx.xx:1/crtl/repo/rhel/9.3le
text
keyboard --vckeymap=us --xlayouts='us'
lang en_US.UTF-8
rootpw --plaintext 111
skipx
timezone Asia/Kolkata --isUtc
zerombr
clearpart --all --initlabel --drives=/dev/disk/by-id/0235b1
bootloader   --location=mbr --boot-drive=/dev/disk/by-id/0235b1
ignoredisk --only-use=/dev/disk/by-id/dm-uuid-mpath-0235b1
autopart --type=lvm --fstype=ext4
services --enabled=NetworkManager,sshd
reboot
%packages
@core
kexec-tools
device-mapper-multipath
%end
%post
sed -i 's/#\?PermitRootLogin.*/PermitRootLogin yes/g' /etc/ssh/sshd_config;service sshd restart;multipath -t >/etc/multipath.conf;service multipathd start
%end
```

**Comment by priyama2** [comment]
Deleted the specified file

**Review by abdhaleegit — CHANGES_REQUESTED** [review]
need few things  before we merge
1. Try one run on SUSE installation
2. we need full instlalation logs for ftp and nfs
3. remove the extra commit 

Thanks

**Comment by PraveenPenguin** [comment]
@priyama2 please wrap changes in commits as something like below and squashed other commit, and we are good to go 
1- Add nfs support 
2- Add FTP support

**Pull request closed without merging**
